# Build image
FROM dockage/mailcatcher:0.9.0

# Install dependencies
RUN apk add --no-cache tzdata

# Set the timezone
ENV TZ=Europe/Bratislava
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Start MailCatcher
EXPOSE 1025 1080
CMD ["mailcatcher", "--no-quit", "--foreground", "--ip=0.0.0.0", "--message-limit=50"]
