services:
    jumpeno:
        container_name: jumpeno
        image: jumpeno
        build:
            context: .
            dockerfile: Dockerfile.jumpeno
        environment:
            ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            EMAIL_BACKUP_KEYS: ${EMAIL_BACKUP_KEYS}
            EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
        restart: always
        ports:
            - 80:80
    database:
        container_name: database
        image: database
        build:
            context: .
            dockerfile: Dockerfile.database
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ${DB_PATH}:/var/lib/mysql
    adminer:
        container_name: adminer
        image: adminer
        build:
            context: .
            dockerfile: Dockerfile.adminer
        restart: always
        ports:
            - 8080:8080
    mailcatcher:
        container_name: mailcatcher
        image: mailcatcher
        build:
            context: .
            dockerfile: Dockerfile.mailcatcher
        restart: always
        ports:
            - 1025:1025 # SMTP server
            - 1080:1080 # Web UI
