services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: jumpeno
        restart: always
        volumes:
            - jumpeno-db:/app/Services/Database/Files
        ports:
            - 80:80
volumes:
    jumpeno-db:
