namespace Jumpeno.Client.Constants;

public enum COLLAPSE_SURFACE {
    PRIMARY_COLLAPSE = SURFACE.PRIMARY_COLLAPSE,
    PRIMARY_BOX_COLLAPSE = SURFACE.PRIMARY_BOX_COLLAPSE,
    PRIMARY_GLASS_COLLAPSE = SURFACE.PRIMARY_GLASS_COLLAPSE,
    FLOATING_COLLAPSE = SURFACE.FLOATING_COLLAPSE,
    FLOATING_ADDITIONAL_COLLAPSE = SURFACE.FLOATING_ADDITIONAL_COLLAPSE
}
