namespace Jumpeno.Client.Constants;

public enum PAGE_LOADER_TASK {
    DEFAULT,
    INITIAL, NAVIGATION, ANIMATION,
    MENU, MODAL, SELECT, COLLAPSE, SEARCH, CONFIRM,
    CULTURE_CHANGE, THEME_CHANGE, COOKIE_CONSENT,
    GAME, GAME_REQUEST,
    LOGIN, LOGOUT, REGISTRATION, ACTIVATION, PASSWORD_RESET,
    PROFILE,
    ADMIN_CREDENTIALS
}
