namespace Jumpeno.Client.Constants;

public enum PAGE_LOADER_TASK {
    DEFAULT,
    INITIAL, NAVIGATION, ANIMATION,
    MENU, MODAL, SELECT, COLLAPSE, SEARCH, CONFIRM,
    CULTURE_CHANGE, THEME_CHANGE, THEME_CHANGE_SWITCH, COOKIE_CONSENT,
    GAME_CONNECT, GAME_REQUEST,
    LOGIN, LOGOUT, REGISTRATION, ACTIVATION, PASSWORD_RESET, USER_UPDATE, DELETE_ACCOUNT, PASSWORD_CHANGE,
    PROFILE,
    ADMIN_CREDENTIALS
}
