namespace Jumpeno.Client.Constants;

public enum PAGE_LOADER_TASK {
    DEFAULT,
    INITIAL, NAVIGATION,
    MENU, MODAL, SELECT, COLLAPSE, SWITCH,
    CULTURE_CHANGE, THEME_CHANGE, COOKIE_CONSENT,
    GAME
}
