name: Dev Build&Deploy

on:
  push:
    branches: [ development ]
  workflow_dispatch: # To run this workflow manually from the Actions tab

jobs:
  build: # Job 1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'development'
      - name: Login to GitHub
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login https://ghcr.io -u $GITHUB_USER -p $GITHUB_PASSWORD
      - name: Build Image
        run: docker build -t ghcr.io/fri-uniza/jumpeno/jumpeno:dev .
      - name: Push Image
        run: docker push ghcr.io/fri-uniza/jumpeno/jumpeno:dev
  deploy: # Job 2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: 'development'
      - name: Push with curl
        uses: wei/curl@v1
        with:
          args: -X POST -k https://portainer.docker.kst.fri.uniza.sk/api/stacks/webhooks/e34f73b7-98cc-4257-be33-20df9a0f02dd
