name: Latest Build&Deploy

on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to GitHub
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login https://docker.pkg.github.com -u $GITHUB_USER -p $GITHUB_PASSWORD

      - name: Build Image
        run: docker build -t docker.pkg.github.com/fri-uniza/jumpeno/jumpeno .

      - name: Push Image
        run: docker push docker.pkg.github.com/fri-uniza/jumpeno/jumpeno

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Push with curl
        uses: wei/curl@master
        with:
          args: -X POST -k https://portainer.docker.kst.fri.uniza.sk/api/stacks/webhooks/e34f73b7-98cc-4257-be33-20df9a0f02dd
