name: Latest Build&Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push event but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains two job called "build" and "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login https://ghcr.io -u $GITHUB_USER -p $GITHUB_PASSWORD

      # Build Image
      - name: Build Image
        run: docker build -t ghcr.io/fri-uniza/jumpeno/jumpeno:latest .
      
      # Push Image
      - name: Push Image
        run: docker push ghcr.io/fri-uniza/jumpeno/jumpeno:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@master
      - name: Push with curl
        uses: wei/curl@master
        with:
          args: -X POST -k https://portainer.docker.kst.fri.uniza.sk/api/stacks/webhooks/e34f73b7-98cc-4257-be33-20df9a0f02dd
