name: Latest Build&Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch: # To run this workflow manually from the Actions tab

jobs:
  build: # Job 1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login https://ghcr.io -u $GITHUB_USER -p $GITHUB_PASSWORD
      - name: Build Image
        run: docker build -t ghcr.io/fri-uniza/jumpeno/jumpeno:latest .
      - name: Push Image
        run: docker push ghcr.io/fri-uniza/jumpeno/jumpeno:latest
  deploy: # Job 2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Push with curl
        uses: wei/curl@master
        with:
          args: -X POST -k https://portainer.docker.kst.fri.uniza.sk/api/stacks/webhooks/e34f73b7-98cc-4257-be33-20df9a0f02dd
